# docker/Dockerfile.backend
FROM python:3.11-slim

WORKDIR /app

COPY ../backend /app

# Ajout de pymongo pour MongoDB
RUN pip install --no-cache-dir -r requirements.txt pymongo

EXPOSE 5000

CMD ["python", "app.py"]