version: "3.8"

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: smartscraper-backend
    ports:
      - "5000:5000"
    volumes:
      - dbdata:/app/db
    working_dir: /app
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    container_name: smartscraper-frontend
    ports:
      - "3000:80"

  cron:
    build:
      context: ../..
      dockerfile: smartscraper/docker/Dockerfile.cron
    container_name: smart_cron

  mongodb:
    image: mongo:7
    container_name: smartscraper-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  dbdata:
  mongodb_data:
