# docker/Dockerfile.frontend
FROM node:20 AS build

WORKDIR /app

COPY ../frontend /app

RUN npm install && npm run build

# Étape de production : servir le build statique
FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80
